### ISSUE TITLE
Notebooks in different directories

### ISSUE THREAD

**Issue by itsinder** [tfiz/lupyter#1]
If you create a jupyter notebook in any other folder except lupyter it errors out. (In this case the folder is NoteBooks)
[W 16:07:35.627 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161006160723 (::1) 14.82ms referer=http://localhost:8888/notebooks/NoteBooks/Untitled.ipynb
[I 16:07:38.610 NotebookApp] KernelRestarter: restarting kernel (1/5)
/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'luakernel.py': [Errno 2] No such file or directory

Followed all the intructions listed on the homepage.

**Comment by tomstitt** [comment]
Good catch, I never even tried somewhere else.  The .py kernel file is now installed alongside the python lua wrapper.  It appears to function now, you can launch the notebook from where ever after installing.

**Comment by itsinder** [comment]
works like a charm, thanks
